[package]
name = "hex_pixel_editor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macroquad = { version = "0.4", default-features = false }
png = "0.17"
rgb = "0.8"
imgref = "1.9"
anyhow = "1.0"
