[package]
name = "hex_pixel_editor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macroquad = "0.3"
png = "0.17"
rgb = "0.8"
imgref = "1.9"
